artifiacts_root: artifiacts


data_ingestion:
  root_dir: artifiacts/data_ingestion
  source_URL: https://drive.google.com/file/d/18eF_QZvphD-vkrP_sQBXNOaV-TYnMPX-/view?usp=sharing
  local_data_file: artifiacts/data_ingestion/data.zip
  unzip_dir: artifiacts/data_ingestion


prepare_base_model:
  root_dir: artifiacts/prepare_base_model
  base_model_path: artifiacts/prepare_base_model/base_model.h
  updated_base_model_path: artifiacts/prepare_base_model/base_model_updated.h5


training:
  root_dir: artifiacts/training
  trained_model_path: artifiacts/training/model.h5


